# Generated by Django 4.2.2 on 2023-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_wall'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_summary', models.TextField()),
                ('apply_link', models.URLField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
