# Generated by Django 4.2.2 on 2023-06-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_title',
            field=models.CharField(default='Not Disclosed', max_length=100),
        ),
    ]
