# Generated by Django 4.2.2 on 2023-06-25 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_jobpost_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friendships',
            field=models.ManyToManyField(through='user.Connection', to=settings.AUTH_USER_MODEL),
        ),
    ]
